version: "3.8"
services:
  conversion-grpc:
    build: .
    restart: on-failure
    container_name: conversion_grpc
    command: sh -c "go build -o grpc main.go && ./grpc"
    volumes:
      - .:/go/src/app
    ports:
      - $GRPC_PORT:$GRPC_PORT
    env_file: .env
    networks:
      - shared-network

networks:
  shared-network:
    external: true
