version: "3.8"
services:
  content-db:
    container_name: content_db
    restart: always
    image: postgres:16.1-alpine3.18
    volumes:
      - content_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $DB_NAME -U $DB_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  content-redis:
    container_name: content_redis
    restart: always
    image: redis:7.2.3-alpine
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  content-app:
    build: .
    restart: on-failure
    container_name: content_app
    command: sh -c "goose -dir ./sql/schema/ postgres $DB_URL up && go build -o http main.go && ./http"
    volumes:
      - .:/go/src/app
    ports:
      - $HTTP_PORT:$HTTP_PORT
    env_file: .env
    depends_on:
      content-db:
        condition: service_healthy
      content-redis:
        condition: service_healthy
    networks:
      - internal
      - shared-network

volumes:
  content_db:

networks:
  internal:
    driver: bridge
  shared-network:
    external: true
