// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID         pgtype.UUID
	CreatedAt  pgtype.Timestamp
	ModifiedAt pgtype.Timestamp
	Email      string
	Password   string
	Name       pgtype.Text
}
